from importlib.metadata import PackageNotFoundError, version as _distribution_version

from . import cuda, map_algebra, spice
from .alignment import (
    align,
    available_resampling_algorithms,
    require_same_grid,
    same_grid,
)
from .errors import (
    AlignmentError,
    ComputeBackendError,
    CoordinateTransformError,
    CudaError,
    DistanceFieldError,
    GeoReferenceError,
    GeoTiffBandError,
    GeoTiffDataTypeError,
    GeoTiffError,
    GeoTiffMetadataError,
    GeoTiffOpenError,
    GeoTiffWriteError,
    GridMismatchError,
    GridError,
    HorizonError,
    HorizonFormatError,
    HorizonGenerationError,
    InputError,
    LunarscoutError,
    MapAlgebraDTypeError,
    MapAlgebraError,
    MapAlgebraExpressionError,
    MapAlgebraGridError,
    MapAlgebraOperationError,
    MapAlgebraStorageError,
    MapAlgebraUnitError,
    OutputExistsError,
    OperationCancelledError,
    ProductCalculationError,
    ProductCatalogError,
    ProductError,
    ProductStorageError,
    ProductTimeError,
    RasterValidationError,
    RegionOperationError,
    ScenarioError,
    ScenarioPathError,
    ScenarioStateError,
    SpiceError,
    SpiceGeometryError,
    SpiceKernelError,
    TemporalCubeError,
    TemporalError,
    TemporalOperationError,
    TemporalLookupError,
    TemporalSeriesError,
    TemporalSeriesOpenError,
    TemporalSeriesWriteError,
    TerrainOperationError,
    TimeRangeError,
    VectorError,
)
from .georeference import GeoReference
from .geotiff import read_geotiff, write_geotiff
from .horizon import generate_horizons
from .map_products import (
    MapProduct,
    MapProductCatalog,
    MapRegion,
    download_map_product,
    filesystem_safe_scenario_name,
    load_map_product_catalog,
    map_product_download_directory,
    map_product_scenario_name,
    search_map_products,
)
from .products import (
    generate_earth_elevation,
    generate_lightmap,
    generate_psr,
    generate_safe_havens,
    generate_sun_elevation,
    mission_duration_from_sun_and_earth_elevation,
    mission_duration_from_sun_elevation,
    mission_duration_from_sunlight,
    mission_duration_from_sunlight_and_earth_elevation,
)
from .progress import ProgressEvent
from .raster import Raster
from .regions import (
    filter_regions_by_size,
    find_borders,
    label_regions,
    region_sizes,
)
from .scenario import Scenario, open_scenario
from .spice_geometry import (
    LonLat,
    body_azimuth_elevation,
    body_azimuth_elevation_dataframe,
    body_azimuth_elevation_over_horizon,
    body_vectors_ned,
    body_vectors_ned_dataframe,
    body_vectors_moon_me,
    iter_times,
    plot_body_elevation,
    plot_body_elevations,
    sunlight_fraction,
)
from .temporal import (
    TemporalCube,
    TimeRange,
    temporal_max,
    temporal_mean,
    temporal_min,
    temporal_std,
    times,
    utc_datetime,
)
from .temporal_store import (
    TemporalGeoTiffSeriesWriter,
    TemporalGeoTiffSeries,
    TemporalWriteProgress,
    open_temporal_cube,
    write_temporal_cube,
)
from .terrain import aspect, hillshade, slope

__all__ = [
    "__version__",
    "AlignmentError",
    "ComputeBackendError",
    "CoordinateTransformError",
    "CudaStatus",
    "CudaError",
    "DistanceFieldError",
    "GeoReference",
    "GeoReferenceError",
    "GeoTiffBandError",
    "GeoTiffDataTypeError",
    "GeoTiffError",
    "GeoTiffMetadataError",
    "GeoTiffOpenError",
    "GeoTiffWriteError",
    "GridMismatchError",
    "GridError",
    "HorizonError",
    "HorizonFormatError",
    "HorizonGenerationError",
    "InputError",
    "LunarscoutError",
    "LonLat",
    "MapAlgebraDTypeError",
    "MapAlgebraError",
    "MapAlgebraExpressionError",
    "MapAlgebraGridError",
    "MapAlgebraOperationError",
    "MapAlgebraStorageError",
    "MapAlgebraUnitError",
    "MapProduct",
    "MapProductCatalog",
    "MapRegion",
    "OutputExistsError",
    "OperationCancelledError",
    "ProductCalculationError",
    "ProductCatalogError",
    "ProductError",
    "ProductStorageError",
    "ProductTimeError",
    "ProgressEvent",
    "Raster",
    "RasterValidationError",
    "RegionOperationError",
    "Scenario",
    "ScenarioError",
    "ScenarioPathError",
    "ScenarioStateError",
    "SpiceError",
    "SpiceGeometryError",
    "SpiceKernelError",
    "TemporalCube",
    "TemporalCubeError",
    "TemporalError",
    "TemporalOperationError",
    "TemporalGeoTiffSeries",
    "TemporalGeoTiffSeriesWriter",
    "TemporalLookupError",
    "TemporalSeriesError",
    "TemporalSeriesOpenError",
    "TemporalSeriesWriteError",
    "TemporalWriteProgress",
    "TerrainOperationError",
    "TimeRange",
    "TimeRangeError",
    "VectorError",
    "align",
    "aspect",
    "available_resampling_algorithms",
    "body_azimuth_elevation",
    "body_azimuth_elevation_dataframe",
    "body_azimuth_elevation_over_horizon",
    "body_vectors_ned",
    "body_vectors_ned_dataframe",
    "body_vectors_moon_me",
    "cuda",
    "download_map_product",
    "filesystem_safe_scenario_name",
    "filter_regions_by_size",
    "find_borders",
    "generate_lightmap",
    "generate_horizons",
    "generate_psr",
    "generate_safe_havens",
    "generate_earth_elevation",
    "generate_sun_elevation",
    "mission_duration_from_sun_and_earth_elevation",
    "mission_duration_from_sun_elevation",
    "mission_duration_from_sunlight",
    "mission_duration_from_sunlight_and_earth_elevation",
    "hillshade",
    "iter_times",
    "label_regions",
    "load_map_product_catalog",
    "map_algebra",
    "map_product_download_directory",
    "map_product_scenario_name",
    "open_scenario",
    "open_temporal_cube",
    "plot_body_elevation",
    "plot_body_elevations",
    "read_geotiff",
    "region_sizes",
    "require_same_grid",
    "same_grid",
    "search_map_products",
    "slope",
    "spice",
    "sunlight_fraction",
    "temporal_max",
    "temporal_mean",
    "temporal_min",
    "temporal_std",
    "times",
    "utc_datetime",
    "write_geotiff",
    "write_temporal_cube",
]

# Kept as a root-level diagnostic type while capability functions stay under
# ``ls.cuda``. Importing the type does not import Numba or initialize CUDA.
CudaStatus = cuda.CudaStatus

try:
    __version__ = _distribution_version("lunarscout")
except PackageNotFoundError:
    # A source tree copied without its generated egg-info remains importable.
    __version__ = "0+unknown"
